# Generated by Django 4.2.9 on 2024-01-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_rfid_id_remove_users_userid_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Runners',
        ),
    ]
