# Generated by Django 4.2.9 on 2024-01-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_runners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EPC_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rfid')),
                ('UserID_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
