# Generated by Django 4.2.9 on 2024-02-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_runners'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='FirstName',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='LastName',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
